### ISSUE TITLE
有谁今天抢到了，帮忙发一下日志 

### ISSUE THREAD

**Issue by dandyhuang** [ztino/helloworld#31]
如题

**Comment by silencesdg** [comment]
返回都是90008，完蛋

**Comment by dandyhuang** [comment]
> 返回都是90008，完蛋

90008是什么意思，没有抢到，再接再厉？

**Comment by dandyhuang** [comment]
返回信息:{"errorMessage":"很遗憾没有抢到，再接再厉哦。","orderId":0,"resultCode":90016,"skuId":0,"success":false}
2021/01/06 10:01:57 抢购失败，返回信息:{"errorMessage":"很遗憾没有抢到，再接再厉哦。","orderId":0,"resultCode":90016,"skuId":0,"success":false}
2021/01/06 10:01:57 获取秒杀初始化信息失败,返回信息:null

**Comment by ztino** [comment]
> 返回信息:{"errorMessage":"很遗憾没有抢到，再接再厉哦。","orderId":0,"resultCode":90016,"skuId":0,"success":false}
> 2021/01/06 10:01:57 抢购失败，返回信息:{"errorMessage":"很遗憾没有抢到，再接再厉哦。","orderId":0,"resultCode":90016,"skuId":0,"success":false}
> 2021/01/06 10:01:57 获取秒杀初始化信息失败,返回信息:null

老哥我抢到了，没抢到的多努力，目前测试脚本可行

**Comment by dandyhuang** [comment]
> > 返回信息:{"errorMessage":"很遗憾没有抢到，再接再厉哦。","orderId":0,"resultCode":90016,"skuId":0,"success":false}
> > 2021/01/06 10:01:57 抢购失败，返回信息:{"errorMessage":"很遗憾没有抢到，再接再厉哦。","orderId":0,"resultCode":90016,"skuId":0,"success":false}
> > 2021/01/06 10:01:57 获取秒杀初始化信息失败,返回信息:null
> 
> 老哥我抢到了，没抢到的多努力，目前测试脚本可行

牛逼

**Comment by samGly** [comment]
我没抢到，返回90016，

**Comment by silencesdg** [comment]
> > 返回都是90008，完蛋
> 
> 90008是什么意思，没有抢到，再接再厉？

90008被风控了

**Comment by dandyhuang** [comment]
> > > 返回都是90008，完蛋
> > 
> > 
> > 90008是什么意思，没有抢到，再接再厉？
> 
> 90008被风控了

你抢了很多天，还是你的账号plus分是多少

**Comment by wzl995516** [comment]
老哥们 运行的实行显示这个是怎么回事 怎么解决啊A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by dandyhuang** [comment]
> 老哥们 运行的实行显示这个是怎么回事 怎么解决啊A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

什么系统的，每次运行都是吗

**Comment by dandyhuang** [comment]
> 老哥们 运行的实行显示这个是怎么回事 怎么解决啊A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

什么系统的，每次运行都是吗
