### ISSUE TITLE
脚本目前可用，附上自己的抢购截图

### ISSUE THREAD

**Issue by ztino** [ztino/helloworld#32]
![微信图片_20210106101450](https://user-images.githubusercontent.com/76823311/103721338-551c4600-4fc5-11eb-9f33-d7f8a8d5e89b.png)

**Comment by ztino** [comment]
大概一会抢到了，抢到程序会自动退出的

**Comment by silenceli** [comment]
cookie.txt 多久过期？

**Comment by ztino** [comment]
其实这个不单纯看小白信用分的，还有看plus的综合分，我这个号小白信用分才70多，plus综合分106

**Comment by ztino** [comment]
没抢到的，多坚持抢一段时间吧，加油，感谢这几天大家的测试

**Comment by fa1com** [comment]
感谢作者付出的努力！👍

**Comment by ztino** [comment]
> cookie.txt 多久过期？

目前不是很清楚，请自行测试

**Comment by flyhong666** [comment]
羡慕啊。。。

**Comment by YuanYoup** [comment]
抢购链接获取失败，稍后自动重试，这是啥原因？

**Comment by hanluner** [comment]
你这个时间是02:00 这个有什么技巧吗？

**Comment by Trig-Von** [comment]
> 你这个时间是02:00 这个有什么技巧吗？

时区不一样，他这个两点就是北京时区的十点

**Comment by silenceli** [comment]
> 抢购链接获取失败，稍后自动重试，这是啥原因？

同遇到这个问题

**Comment by xudai3** [comment]
今天抢到了，多谢老哥

**Comment by wzl995516** [comment]
老哥  小白一个  下完2.1文件  go怎么运行啊  求大佬们教教

**Comment by wzl995516** [comment]
老哥们 运行的实行显示这个是怎么回事 怎么解决啊A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
