### ISSUE TITLE
两个账号的eid和fp都一样咋办

### ISSUE THREAD

**Issue by lijiawang** [ztino/helloworld#38]
两个账号的eid和fp都一样咋办

**Comment by ztino** [comment]
目前推测京东今天在灰度修改eid和fp获取的，目前观望中，获取不到的可以去下了订单输入付款密码的页面手动获取

**Comment by flyhong666** [comment]
这个eid 和fp 获取与账号没有关系的呀。是与浏览器以及版本有关的。

**Comment by S7venYoung** [comment]
目前eid 和fp这两个数据获取不到了

**Comment by flyhong666** [comment]
> 目前eid 和fp这两个数据获取不到了

![2021-01-06_152514](https://user-images.githubusercontent.com/76857714/103741099-71ef6280-5033-11eb-8ab0-0d3b328f63ec.png)
没毛病，能获取到。

**Comment by lijiawang** [comment]
这脚本必须得在有浏览器的服务器执行才行吗，我直接用的服务器，没浏览器可以吗？

**Comment by S7venYoung** [comment]
> > 目前eid 和fp这两个数据获取不到了
> 
> ![2021-01-06_152514](https://user-images.githubusercontent.com/76857714/103741099-71ef6280-5033-11eb-8ab0-0d3b328f63ec.png)
> 没毛病，能获取到。

就是文中介绍的方法吗，我是Mac手动和Windows自动都无法获取

**Comment by flyhong666** [comment]
> 这脚本必须得在有浏览器的服务器执行才行吗，我直接用的服务器，没浏览器可以吗？

那不知道哦。你试试呗。我是自己的电脑运行的。

**Comment by Jawf** [comment]
通过mac chrome浏览器手动获取的eid，fp可以放到ubuntu或centOS服务器上使用吗？

**Comment by linguodong** [comment]
获取不到，eid似乎可以，jd cooike里也有，frp就不知道没招到

**Comment by ztino** [comment]
目前发现fp是根据设备的，eid是针对用户的，每个用户都不一样，但是fp同设备换号是一样的，可能这个大家得注意

**Comment by Emptytao** [comment]
我的eid和fp变过好多次了，
<img width="377" alt="image" src="https://user-images.githubusercontent.com/26384334/103849159-fea32a80-50de-11eb-9996-42637dc2116f.png">
下面是自动获取的
<img width="749" alt="image" src="https://user-images.githubusercontent.com/26384334/103849207-0f53a080-50df-11eb-83f4-6d0ca9157db3.png">

**Comment by Fosrster** [comment]
为什么我自己获取的fp跟软件的不一致，到底是要用我自己获取的，还是用软件的，头好大

**Comment by wxzwolf** [comment]
> 两个账号的eid和fp都一样咋办
我今天发现软件获取的eid和fr和手工查询的不一样，有明白的说一下啥情况？

**Comment by Fosrster** [comment]
看来我们的问题一样，我感觉还是用手工的好点吧

**Comment by ztino** [comment]
> 看来我们的问题一样，我感觉还是用手工的好点吧

查看本问题上面我的回复，有介绍，其实fp个人认为问题不大，但是用其他人的号后，fp不要跟之前的号一样就行
