### ISSUE TITLE
这脚本必须得在有浏览器的服务器执行才行吗

### ISSUE THREAD

**Issue by lijiawang** [ztino/helloworld#39]
这脚本必须得在有浏览器的服务器执行才行吗，我直接用的服务器，没浏览器可以吗？

**Comment by xinghui-hou** [comment]
应该是不行的

**Comment by silenceli** [comment]
浏览器只是为了获取 eid,fp

得到了之后，就不再需要了。

况且，eid fp 可以手动获得，也不依赖软件
