### ISSUE TITLE
我在云服务器Ubuntu16.04运行不了

### ISSUE THREAD

**Issue by cmmqqt** [ztino/helloworld#40]
我按照说说明中的方式一(推荐) 
git clone https://github.com/ztino/jd_seckill.git
cd jd_seckill
go get
在aws云服务器上安装了软件，但是运行jd_seckill reserve的时候总报错（jd_seckill: command not found），求大神指教。

root@ip-172:~/jd_seckill# ls 
cmd  common  conf.ini  go.mod  go.sum  jd_seckill  LICENSE  __MACOSX  main.go  README.md  service
root@ip-172:~/jd_seckill# ls -a
.   cmd     conf.ini  .gitattributes  go.mod  jd_seckill  __MACOSX  README.md
..  common  .git      .gitignore      go.sum  LICENSE     main.go   service
root@ip-172:~/jd_seckill# jd_seckill login
jd_seckill: command not found
root@ip-172:~/jd_seckill#

**Comment by yangyg** [comment]
$GOPATH/bin/jd_seckill
生成的二进制文件应该在gopath下面

**Comment by Jawf** [comment]
export gopath
