### ISSUE TITLE
抢到了，谢谢老哥

### ISSUE THREAD

**Issue by Apurikotto** [ztino/helloworld#43]

**Comment by Apurikotto** [comment]
![QQ截图20210107110111](https://user-images.githubusercontent.com/72537772/103841911-9c8ef900-50cf-11eb-8a30-72bfb64438b5.png)

**Comment by Apurikotto** [comment]
![QQ截图20210107110459](https://user-images.githubusercontent.com/72537772/103842017-d06a1e80-50cf-11eb-9c98-7349d57ce54b.png)

**Comment by Jawf** [comment]
具体什么时间点抢到的？

**Comment by flySnail-jinx** [comment]
发日志

**Comment by Apurikotto** [comment]
[jd_seckill_20210107.log](https://github.com/ztino/helloworld/files/5779105/jd_seckill_20210107.log)
log在这里，删除了订单号和个人隐私

**Comment by yirenyishi** [comment]
发一下你的配置截图可以不，我这好像明显比你要慢一秒

**Comment by Apurikotto** [comment]
config在这里，下面的全没有填
![QQ截图20210107111304](https://user-images.githubusercontent.com/72537772/103842475-5d65a580-50d9-11eb-91bc-d596cf6afdc4.png)

**Comment by qi-zhou** [comment]
我地址管理里面已经设置了默认地址怎么还报这个？ 谁知道还要怎么设置？
￼￼
![image](https://user-images.githubusercontent.com/16607058/103842651-66527900-50d1-11eb-9c4d-8c68bc41bb33.png)

**Comment by yirenyishi** [comment]
> config在这里，下面的全没有填
> ![QQ截图20210107111304](https://user-images.githubusercontent.com/72537772/103842475-5d65a580-50d9-11eb-91bc-d596cf6afdc4.png)

那就是你的电脑性能比我的好，或者网速比我快，我这第四秒的时候才 “获取秒杀初始化信息.” ，而你这3秒的时候都下完单了

**Comment by lllrrr2** [comment]
预约是什么时间搞的，

**Comment by gsgs1594** [comment]
能帮我搞一下吗 十分感谢 有偿

**Comment by yirenyishi** [comment]
> 能帮我搞一下吗 十分感谢 有偿

你直接下载releases修改配置就好了，如果你有开发环境，自己打包也行

**Comment by gsgs1594** [comment]
> > 能帮我搞一下吗十分感谢有偿
> 
> 您直接下载版本修改配置就好了，如果您有开发环境，自己打包也行

我下载了最新版的exe，发现无法自动获取eid fp

**Comment by gsgs1594** [comment]
> > > 能帮我搞一下吗十分感谢有偿
> > 
> > 
> > 您直接下载版本修改配置就好了，如果您有开发环境，自己打包也行
> 
> 我下载了最新版的exe，发现无法自动获取eid fp

然后运行的时候有乱码

**Comment by wenkai86** [comment]
弱弱的 问一下eid =后面的号需要加“”吗？

**Comment by Apurikotto** [comment]
> 弱弱的 问一下eid =后面的号需要加“”吗？

不用

**Comment by yirenyishi** [comment]
> > > 能帮我搞一下吗十分感谢有偿
> > 
> > 
> > 您直接下载版本修改配置就好了，如果您有开发环境，自己打包也行
> 
> 我下载了最新版的exe，发现无法自动获取eid fp

那就手动干预，获取一下
