### ISSUE TITLE
获取秒杀初始化信息失败

### ISSUE THREAD

**Issue by zwf8558** [ztino/helloworld#44]
![image](https://user-images.githubusercontent.com/42018376/103842046-eb3c9300-50cf-11eb-87a5-99ae12175a0c.png)

**Comment by yirenyishi** [comment]
我也遇到了

**Comment by qi-zhou** [comment]
一样，但还提示: `可能你还未设置默认收货地址`  ，我地址管理里已经设置了，不知道这个要在哪里设置？
![image](https://user-images.githubusercontent.com/16607058/103843685-3b692480-50d3-11eb-803c-10826266c377.png)

**Comment by zwf8558** [comment]
明天我单线程跑下看看

**Comment by zhangxilu-pro** [comment]
这个你们解决了吗，大佬们

**Comment by KwakGiyoung** [comment]
자바스크립트

**Comment by Mos21059** [comment]
سلام.لطفا کمک کنید

**Comment by mb199879** [comment]
楼主成功了吗？
