### ISSUE TITLE
Windows上执行不成功[index out of range]

### ISSUE THREAD

**Issue by jackforlit** [ztino/helloworld#45]
Windows上执行不成功[index out of range]
具体错误信息如下：
2021/01/07 10:00:01 抢购链接获取成功:https://marathon.jd.com/captcha.html?skuId=
100012043978&sn=824e8103217adbe512b2a466b294ac0b&from=pc
2021/01/07 10:00:01 访问商品的抢购连接...
2021/01/07 10:00:01 获取秒杀初始化信息...
2021/01/07 10:00:01 访问抢购订单结算页面...
2021/01/07 10:00:01 访问抢购订单结算页面...
panic: runtime error: index out of range [0] with length 0

goroutine 27 [running]:
github.com/ztino/jd_seckill/jd_seckill.(*Seckill).SubmitSeckillOrder(0xc00028cf60, 0x0)
        /Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/jd_seckill/seckill.go:185 +0x3f2a
github.com/ztino/jd_seckill/cmd.task(0xc00028cf60)
        /Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/cmd/seckill.go:99 +0x53
created by github.com/ztino/jd_seckill/cmd.Start
        /Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/cmd/seckill.go:88 +0x228

**Comment by ztino** [comment]
老版本，请用最新版本

**Comment by jackforlit** [comment]
> 老版本，请用最新版本

好的，老哥。。
