### ISSUE TITLE
跑一会就自动退出了，好像还是日志问题

### ISSUE THREAD

**Issue by Johnnychi** [ztino/helloworld#47]
平台：Mac
版本：0.21

日志如下：
```go
2021/01/07 10:00:35.675339 log.go:26: 商品名称:飞天 53%vol  500ml 贵州茅台酒（带杯）
2021/01/07 10:00:35.678008 log.go:26: 抢购链接获取失败，稍后自动重试
2021/01/07 10:00:35.723098 log.go:26: 商品名称:飞天 53%vol  500ml 贵州茅台酒（带杯）
2021/01/07 10:00:35.725143 log.go:26: 抢购链接获取失败，稍后自动重试
panic: open ./logs/jd_seckill_20210107.log: too many open files

goroutine 3955 [running]:
github.com/ztino/jd_seckill/log.Println(0xc00086bcb8, 0x1, 0x1)
	/Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/log/log.go:19 +0x166
github.com/ztino/jd_seckill/jd_seckill.(*Seckill).getSeckillUrl(0xc0002fc010, 0x1, 0x1, 0xc0001aa3d6, 0x30)
	/Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/jd_seckill/seckill.go:86 +0x5f7
github.com/ztino/jd_seckill/jd_seckill.(*Seckill).RequestSeckillUrl(0xc0002fc010)
	/Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/jd_seckill/seckill.go:108 +0x189
github.com/ztino/jd_seckill/cmd.task(0xc0002fc010)
	/Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/cmd/seckill.go:105 +0x2b
created by github.com/ztino/jd_seckill/cmd.Start
	/Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/cmd/seckill.go:96 +0x225
```

**Comment by dandyhuang** [comment]
你这个是哪个版本，有可能是日志库引起的，套接字没有关闭导致的

**Comment by Johnnychi** [comment]
> 你这个是哪个版本，有可能是日志库引起的，套接字没有关闭导致的

就最新版的0.21，macOS 10.15.7，朋友的机器M1上跑也是同样的问题

**Comment by dandyhuang** [comment]
> > 你这个是哪个版本，有可能是日志库引起的，套接字没有关闭导致的
> 
> 就最新版的0.21，macOS 10.15.7，朋友的机器M1上跑也是同样的问题

每次运行都会吗还是抢了一段时间才会

**Comment by dandyhuang** [comment]
35秒是吧，抢了一段时间

**Comment by dandyhuang** [comment]
![image](https://user-images.githubusercontent.com/12603054/103891953-ae02f000-5125-11eb-87d2-01736e185934.png)
你看下ulimit -a你是不是文件打开有限制，设置成无限制，因为限制log每次都打开写，会暂用套接字，后面看下怎么优化

**Comment by Johnnychi** [comment]
> ![image](https://user-images.githubusercontent.com/12603054/103892566-c32c4e80-5126-11eb-9b73-9d546e5a9cf3.png)
> 
> 你看下ulimit -a你是不是文件打开有限制，设置成无限制，因为限制log每次都打开写，会暂用套接字，后面看下怎么优化

我今天尝试调大点试试，ulimit -n 默认是256

**Comment by dandyhuang** [comment]
> > ![image](https://user-images.githubusercontent.com/12603054/103892566-c32c4e80-5126-11eb-9b73-9d546e5a9cf3.png)
> > 你看下ulimit -a你是不是文件打开有限制，设置成无限制，因为限制log每次都打开写，会暂用套接字，后面看下怎么优化
> 
> 我今天尝试调大点试试，ulimit -n 默认是256

256他每次写日志都会占用的，肯定就超过了，调整成unlimited就好了

**Comment by llyp** [comment]
不是日志打开文件的过多的问题，是 response 的Body 没有close的问题，导致的文件描述符占用过多
![image](https://user-images.githubusercontent.com/17312537/103966328-9ca7fb00-519a-11eb-8ccf-bd7e215ee2f2.png)

**Comment by llyp** [comment]
像这种请求
![image](https://user-images.githubusercontent.com/17312537/103966419-ca8d3f80-519a-11eb-9731-1e1f8d2d7db6.png) 
第一个返回值是 response  ,下边加一行   defer resp.Body.Close()  就能解决

**Comment by dandyhuang** [comment]
> 不是日志打开文件的过多的问题，是 response 的Body 没有close的问题，导致的文件描述符占用过多
> ![image](https://user-images.githubusercontent.com/17312537/103966328-9ca7fb00-519a-11eb-8ccf-bd7e215ee2f2.png)

哪个接口

**Comment by llyp** [comment]
这个截图是 http.Response 的Body的描述， 说 这个Body是个ReaderCloser 是需要关闭的， 所以在所有发起了http request的地方 就必须对 response的 Body进行关闭，  这个Body 会占用文件描述符， 占用太多不释放， 就会把那个错；
jd_seckill/jd_seckill/seckill.go   这个文件中所有  发请求的地方都需要处理

**Comment by ztino** [comment]
周末我看下这个问题

**Comment by dandyhuang** [comment]
> 这个截图是 http.Response 的Body的描述， 说 这个Body是个ReaderCloser 是需要关闭的， 所以在所有发起了http request的地方 就必须对 response的 Body进行关闭， 这个Body 会占用文件描述符， 占用太多不释放， 就会把那个错；
> jd_seckill/jd_seckill/seckill.go 这个文件中所有 发请求的地方都需要处理

ok.知道了是这个人封装的http库的问题，github.com/Albert-Zhan/httpc
this.httpc.client.Do(this.request) 等估计很多方法用的都有问题，这边需要改一下。大佬强呀

**Comment by KwakGiyoung** [comment]
Okay!!

**Comment by HOOKDLL** [comment]
今天设置时间为: 100 抢一会就崩了

**Comment by HOOKDLL** [comment]
![image](https://user-images.githubusercontent.com/39880388/104006291-40b49500-51e1-11eb-8e91-a918c416673d.png)
# 每次抢购间隔时间，单位:毫秒，默认1500毫秒，每1000毫秒等于1秒
ticker_time = 100
必崩

**Comment by HOOKDLL** [comment]
![image](https://user-images.githubusercontent.com/39880388/104006493-8709f400-51e1-11eb-862c-a05144a960f9.png)

 每次抢购间隔时间，单位:毫秒，默认1500毫秒，每1000毫秒等于1秒
ticker_time = 100

必崩

**Comment by KwakGiyoung** [comment]
How should I do?

2021년 1월 8일 (금) 오후 7:45, Small-Q <notifications@github.com>님이 작성:

**Comment by ztino** [comment]
最新代码以解决该问题
