### ISSUE TITLE
自动获取eid和fp失败

### ISSUE THREAD

**Issue by skpyt** [ztino/helloworld#51]

**Comment by ywanbing** [comment]
根据教程手动去获取，然后写入 config.ini 的配置文件中

**Comment by skpyt** [comment]
> 根据教程手动去获取，然后写入config.ini的配置文件中

maotai秒杀的商品手动获取是空的，没东西，无法加入购物车，到不了下单的页面，其他商品手动倒是能获取出来。

**Comment by ywanbing** [comment]
根据之前作者说的  你在任意商品中获取的 eid 和 fp 都是一样的； 所以你不用纠结。

**Comment by skpyt** [comment]
> 根据之前作者说的你在任意商品中获取的eid和fp都是一样的；所以你不用纠结。

好吧，试了下还真是，谢谢大佬
