### ISSUE TITLE
会话失效, 程序自动退出

### ISSUE THREAD

**Issue by jicki** [ztino/helloworld#52]
2021/01/07 09:09:07.716465 log.go:26: 加载cookie成功
2021/01/07 09:09:08.182980 log.go:26: 正在等待到达设定时间:2021-01-07 09:59:59，检测本地时间与京东服务器时间误差为【-133】毫秒
2021/01/07 09:39:13.651489 log.go:26: 会话失效,程序自动退出

**Comment by ywanbing** [comment]
重新登录试试

**Comment by ztino** [comment]
正常现象，程序启动等待抢购时，会检测你的会话是否失效的，失效了后面抢购也没意义了
