### ISSUE TITLE
抢购失败，请重新登录

### ISSUE THREAD

**Issue by zhangguanzhang** [ztino/helloworld#60]
![image](https://user-images.githubusercontent.com/18641678/103965121-04107b80-5198-11eb-9502-85172ac49c98.png)
ctrl + c 后cookie文件消失

**Comment by httpcheck** [comment]
+1，mac上登录后，复制cookie在服务器上运行出现如上问题。
ps：我一同事也是将cookie文件放在服务器上，今天抢到了俩茅台~

**Comment by Fosrster** [comment]
一个账号，2个地方同时抢有没问题
