### ISSUE TITLE
抢购结束了日志文件是空的，运行环境mac

### ISSUE THREAD

**Issue by RoseEnd** [ztino/helloworld#61]

**Comment by 1114619217** [comment]
windows日志文件也是空的，日志输出在控制台

**Comment by Fosrster** [comment]
有日志啊，就是抢购失败，看来软件都无能为力了

**Comment by RoseEnd** [comment]
日志都在控制台，日志文件里面没有

**Comment by Fosrster** [comment]
![image](https://user-images.githubusercontent.com/5330337/103966329-9ca7fb00-519a-11eb-8f7c-77889d30e102.png)
我这边有日志就是抢购失败，有人抢成功了吗

**Comment by 1114619217** [comment]
> 日志都在控制台，日志文件里面没有

![image](https://user-images.githubusercontent.com/18638991/103966395-bf3a1400-519a-11eb-8384-789689bf2e58.png)
我着日志文件都是空的。没抢到

**Comment by RoseEnd** [comment]
我也是这样

**Comment by Fosrster** [comment]
用这个软件抢会不会黑号啊~_~

**Comment by 1114619217** [comment]
> 我也是这样

明天继续

**Comment by Fosrster** [comment]
> > 我也是这样
> 
> 明天继续
我担心会不会黑号，有没人试过抢成功的

**Comment by 1114619217** [comment]
> > > 我也是这样
> > 
> > 
> > 明天继续
> > 我担心会不会黑号，有没人试过抢成功的

昨天有人抢到过，今天不知道。管他黑不黑的，反正手动抢也抢不到

**Comment by RoseEnd** [comment]
这个日志很乱啊，作者不能每个goroutione分开记录日志嘛，现在一堆在里面

**Comment by Fosrster** [comment]
狮子和猫，有没这个

**Comment by Mos21059** [comment]
راهنمایی کنید
