### ISSUE TITLE
抢购失败，返回一大片html

### ISSUE THREAD

**Issue by flySnail-jinx** [ztino/helloworld#62]
![图片](https://user-images.githubusercontent.com/19680758/103966056-0ffd3d00-519a-11eb-838f-3c546eb20d06.png)

**Comment by Lstoryc** [comment]
相同

**Comment by yirenyishi** [comment]
昨天就有这个问题了

**Comment by yvlf** [comment]
相同

**Comment by silenceli** [comment]
同遇到

**Comment by Fosrster** [comment]
同样，而且经常链接获取失败：
2021/01/08 09:59:58.030907 log.go:26: 抢购链接获取失败，稍后自动重试
2021/01/08 09:59:58.055892 log.go:26: 抢购链接获取失败，稍后自动重试
2021/01/08 09:59:58.055892 log.go:26: 抢购链接获取失败，稍后自动重试
2021/01/08 09:59:58.072882 log.go:26: 抢购链接获取失败，稍后自动重试
2021/01/08 09:59:58.094869 log.go:26: 抢购链接获取失败，稍后自动重试
2021/01/08 09:59:58.117856 log.go:26: 抢购链接获取失败，稍后自动重试

**Comment by dandyhuang** [comment]
这是因为有时候返回首页链接信息，后面可以把这个打印去掉

**Comment by Mos21059** [comment]
سر در نمیارم. لطفا‌ کمک کنید☹☹
