### ISSUE TITLE
配置文件不存在，程序退出

### ISSUE THREAD

**Issue by caoler** [ztino/helloworld#63]
![lSxn10](https://szmapp.oss-cn-shenzhen.aliyuncs.com/uPic/lSxn10.png)

**Comment by caoler** [comment]
mac版，下载后手动配置完ini文件之后，运行主程序直接提示配置文件不存在，程序退出

**Comment by caoler** [comment]
@ztino  这么冷漠的吗？直接关闭

**Comment by ztino** [comment]
> @ztino 这么冷漠的吗？直接关闭
关闭的问题有类似的回答，还有请注意查看描述文件，里面有写如何运行
这里再给你回答下，软件目录下执行ls -a查看下是否有conf.ini
