### ISSUE TITLE
抢到了 特来感谢

### ISSUE THREAD

**Issue by weizifen** [ztino/helloworld#69]
![1501610090280_ pic_hd](https://user-images.githubusercontent.com/21212259/103985922-cd9d2580-51c4-11eb-8393-db5710037f1c.jpg)

**Comment by LaoFang1s** [comment]
这是放容器里跑的吗

**Comment by weizifen** [comment]
> 这是放容器里跑的吗

本地跑 goland

**Comment by ztino** [comment]
他这个是2.0.0的所以日志时间是utc

**Comment by LaoFang1s** [comment]
> 他这个是0.2.0的所以日志时间是utc

怪不得

**Comment by HOOKDLL** [comment]
我没抢到是跟小白信用有关系么?

**Comment by zhuimingzhenbai202** [comment]
> > 这是放容器里跑的吗
> 
> 
> 
> 本地跑 goland

咋弄

**Comment by Mos21059** [comment]
راهنمایی کنید لطفا
☹☹☹☹☹

**Comment by MrChangMM** [comment]
本地go lang 下载依赖失败啊！

helloworld-main\jd_seckill>go get
go: github.com/Albert-Zhan/httpc@v0.0.0-20210108124012-d3f23351b50f: Get "https://proxy.golang.org/github.com/%21albert-%21zhan/httpc/@v/v0.0.0-20210108124012-d3f23351b50f.mod": dial tcp 172.217.27.145:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

怎么破？？？

**Comment by ruixule** [comment]
> 本地go lang 下载依赖失败啊！
> 
> helloworld-main\jd_seckill>go get
> go: github.com/Albert-Zhan/httpc@v0.0.0-20210108124012-d3f23351b50f: Get "https://proxy.golang.org/github.com/%21albert-%21zhan/httpc/@v/v0.0.0-20210108124012-d3f23351b50f.mod": dial tcp 172.217.27.145:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
> 
> 怎么破？？？

这个你就代理下就好了

**Comment by ShiMinghao0208** [comment]
> > 本地go lang 下载依赖失败啊！
> > helloworld-main\jd_seckill>go get
> > go: github.com/Albert-Zhan/httpc@v0.0.0-20210108124012-d3f23351b50f: Get "https://proxy.golang.org/github.com/%21albert-%21zhan/httpc/@v/v0.0.0-20210108124012-d3f23351b50f.mod": dial tcp 172.217.27.145:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
> > 怎么破？？？
> 
> 这个你就代理下就好了

老哥我挂了代理，go get一直卡在那没反应了，这玩意大概得下多久啊

**Comment by ruixule** [comment]
> > > 本地go lang 下载依赖失败啊！
> > > helloworld-main\jd_seckill>go get
> > > go: github.com/Albert-Zhan/httpc@v0.0.0-20210108124012-d3f23351b50f: Get "https://proxy.golang.org/github.com/%21albert-%21zhan/httpc/@v/v0.0.0-20210108124012-d3f23351b50f.mod": dial tcp 172.217.27.145:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
> > > 怎么破？？？
> > 
> > 
> > 这个你就代理下就好了
> 
> 老哥我挂了代理，go get一直卡在那没反应了，这玩意大概得下多久啊

加下QQ 我远程看下 1414100586

**Comment by linguodong** [comment]
fp现在怎么获取啊，获取不到了好像京东更新了。

**Comment by ruixule** [comment]
> fp现在怎么获取啊，获取不到了好像京东更新了。

么有呀 远程看下

**Comment by ruixule** [comment]
> > fp现在怎么获取啊，获取不到了好像京东更新了。
> 
> 么有呀 远程看下

参数和以前一样啊 ，很简单的就获取到了

**Comment by linguodong** [comment]
> > > fp现在怎么获取啊，获取不到了好像京东更新了。
> > 
> > 
> > 么有呀 远程看下
> 
> 参数和以前一样啊 ，很简单的就获取到了

试了第二次可以获取到了，之前看另外一个项目脚本的教程用chrome console没法找到...
明天抢看看，希望能抢到

**Comment by mb199879** [comment]
抢了几天抢到的
