### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by MrChangMM** [ztino/helloworld#74]
helloworld-main\helloworld-main\jd_seckill 的目录

2021/周六/01/09  03:54    <DIR>          .
2021/周六/01/09  03:54    <DIR>          ..
2021/周六/01/09  03:54            15,525 seckill.go
2021/周六/01/09  03:54             1,960 session.go
2021/周六/01/09  03:54             5,984 user.go
               3 个文件         23,469 字节
               2 个目录 51,124,830,208 可用字节

E:\source\helloworld-main\helloworld-main\jd_seckill>go get
go: github.com/Albert-Zhan/httpc@v0.0.0-20210108124012-d3f23351b50f: Get "https://proxy.golang.org/github.com/%21albert-%21zhan/httpc/@v/v0.0.0-20210108124012-d3f23351b50f.mod": dial tcp 142.250.199.81:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by pppscn** [comment]
没有梯子就用go代理

go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.io,direct
