### ISSUE TITLE
请问扫码成功，但是无法登录是怎么回事啊？

### ISSUE THREAD

**Issue by Vidarshui** [ztino/helloworld#79]
2021-01-10 23:01:13.416	ERROR	二维码信息校验失败
2021-01-10 23:01:13.416	ERROR	登录失败

**Comment by GYHiroko** [comment]
可以给个电报链接吗？以后是在那里发布更新吗？

**Comment by ztino** [comment]
> 可以给个电报链接吗？以后是在那里发布更新吗？

你来晚了，暂不对外开放
