### ISSUE TITLE
抢到了，特来感谢！

### ISSUE THREAD

**Issue by MingDemon411** [ztino/helloworld#82]
之前用jd_seckill抢了一个星期也没有抢到，今天第一次用这就抢到了。十分感谢！
![QQ截图20210111101019](https://user-images.githubusercontent.com/48229057/104142352-1fa39e00-53b3-11eb-9d3a-edd8991dd14d.png)

**Comment by Lstoryc** [comment]
哇 大佬 膜拜///

**Comment by lg920810** [comment]
请问你的小白信用多少啊？我这个错误码总是90008和90016

**Comment by MingDemon411** [comment]
> 请问你的小白信用多少啊？我这个错误码总是90008和90016

信用分就89分，我上个星期用jd_seckill时也全是90008和90016.

**Comment by MingDemon411** [comment]
> 哇 大佬 膜拜///

嘿嘿，你也能抢到的，加油啊

**Comment by linux0x5c** [comment]
京东plus综合分数多少？

**Comment by lvfengyi** [comment]
请问eip fp值采用的自动获取 还是 控制台手动获取的
因为我看今天的参数又变了

**Comment by mb199879** [comment]
jd_seckill 用的哪个版本

**Comment by MingDemon411** [comment]
> 京东plus综合分数多少？

这个我找了好久也不知道在哪里看..

**Comment by MingDemon411** [comment]
> 请问eip fp值采用的自动获取 还是 控制台手动获取的
> 因为我看今天的参数又变了

我好像是自动获取的 昨天才看到这个帖子，然后按照步骤来自动获取

**Comment by MingDemon411** [comment]
> jd_seckill 用的哪个版本

0.24稳定版

**Comment by LaoFang1s** [comment]
大佬你抢购间隔设置多少毫秒？

**Comment by MingDemon411** [comment]
> 大佬你抢购间隔设置多少毫秒？

我都是默认设置没调过

**Comment by Simon-Leeeeeeeee** [comment]
配置需要加双引号吗。。

**Comment by MingDemon411** [comment]
> 配置需要加双引号吗。。

不需要的

**Comment by mumuxiang** [comment]
没抢到，还是要看人品啊，比手动点轻松点。。。
