### ISSUE TITLE
抢购失败后会出现很多乱码。。。

### ISSUE THREAD

**Issue by benji1986** [ztino/helloworld#89]
一抢购失败后就出来一大堆乱码。。我看我这出来了两次抢购失败。。。差不多1.30秒才算开始抢
![image](https://user-images.githubusercontent.com/77263720/104260420-71851a80-54be-11eb-88eb-5a2a5af6ec49.png)
![image](https://user-images.githubusercontent.com/77263720/104260439-7c3faf80-54be-11eb-9722-8870799b664c.png)

**Comment by ztino** [comment]
该问题在最新版已修复

**Comment by benji1986** [comment]
好吧。。感谢
主要是懒得配置go环境了 用的exe版的
