### ISSUE TITLE
今天没人发抢到的,我来发吧,第一次遇到这么快抢到的号

### ISSUE THREAD

**Issue by ztino** [ztino/helloworld#92]
![image_2021-01-12_10-16-33](https://user-images.githubusercontent.com/76823311/104261615-da986e00-547d-11eb-8568-04c9d1565dca.png)
主要看号，这个我朋友的号，一回车就抢到了，时间59秒那是我本地时间不准，很快没有几个请求，他一次也没抢过，第一次上我这个脚本，仅供参考

**Comment by wyd-case** [comment]
你的号抢几天了 之前自己的号抢到过吗 你这个朋友的号抢购时的参数做了什么特殊配置了吗 比如每隔多长时间抢

**Comment by mumuxiang** [comment]
感觉，启动这一下是不是还有优化空间哈？
![image](https://user-images.githubusercontent.com/77255447/104263568-cdeb3880-54c4-11eb-99df-41435975f5fe.png)

**Comment by mumuxiang** [comment]
就是说还是要看号，程序只能提高效率，最终能不能中还是要看京东吧？

**Comment by ztino** [comment]
对的，现在程序只是辅助

**Comment by 6LWa6ZKx** [comment]
> 对的，现在程序只是辅助

啥时候在开放下电报链接呀，老哥。

**Comment by he1229639121** [comment]
不是用app才能抢吗，这个可以模拟app的吗
